# Generated by Django 5.2.3 on 2025-06-30 03:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', '公'), ('F', '母'), ('UNK', '未知')], default='M', max_length=3)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pet_photos/')),
                ('birth_day', models.DateField()),
                ('favorite_food', models.CharField(blank=True, choices=[('RC', '皇家'), ('HILLS', '希爾思'), ('ORIJEN', '渴望'), ('NUTRAM', '紐頓')], max_length=10)),
                ('memo', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
                ('pet_species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets_of_species', to='pets.petspecies')),
                ('pet_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets_of_type', to='pets.pettype')),
            ],
        ),
        migrations.CreateModel(
            name='InjectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injection_type', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('injection_date', models.DateField(default=django.utils.timezone.now, verbose_name='施打日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injection_logs', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('photo_records', models.ImageField(blank=True, null=True, upload_to='health_log_photos/')),
                ('action', models.CharField(choices=[('SEE_DOCTOR', '就醫'), ('OBSERVATE', '觀察'), ('NORMAL', '正常')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='pets.pet')),
            ],
        ),
        migrations.AddField(
            model_name='petspecies',
            name='pet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='pets.pettype'),
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recorded_at', models.DateField(default=django.utils.timezone.now)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='pets.pet')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
