# Generated by Django 5.2.3 on 2025-07-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthlog',
            name='case_closed',
            field=models.BooleanField(default=False, verbose_name='是否結案'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='favorite_food',
            field=models.CharField(blank=True, choices=[('RC', '皇家'), ('HILLS', '希爾思'), ('ORIJEN', '渴望'), ('NUTRAM', '紐頓'), ('CATPOOL', '貓侍'), ('NUTRIENCE', '紐崔斯')], max_length=10),
        ),
    ]
