# Generated by Django 5.2.3 on 2025-06-29 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectionlog',
            name='injection_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='施打日期'),
        ),
    ]
