# Generated by Django 5.2.3 on 2025-06-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_injectionlog_injection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='memo',
            field=models.TextField(blank=True, verbose_name='備註'),
        ),
    ]
