# Generated by Django 5.2.3 on 2025-07-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_healthlog_case_closed_alter_pet_favorite_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='sterilised',
            field=models.BooleanField(default=False, verbose_name='已絕育'),
        ),
    ]
